/* BSDC — Bangladesh Software Development Community. Copyright (c) RRC Development. Proprietary — see LICENSE. */
import { jsPDF } from 'jspdf';
import { generateQrDataUrl } from './qr-generator';
import { APP_URL } from '@/config/constants';
import { formatDate } from './utils';

export interface ReportSection {
  title: string;
  rows: { label: string; value: string }[];
}

export interface ReportInput {
  title: string;
  subtitle: string;
  period: string;
  generatedBy: string;
  sections: ReportSection[];
  chartImages?: { title: string; dataUrl: string }[];
}

function drawHeader(doc: jsPDF, title: string, subtitle: string, period: string): number {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(10, 143, 63);
  doc.rect(0, 0, w, 34, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('BSDC', 14, 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('Bangladesh Software Development Community — RRC Development', 14, 22);
  doc.setFontSize(7);
  doc.text(`Report: ${period} · Generated ${formatDate(Date.now(), 'MMM D, YYYY h:mm A')}`, 14, 28);
  doc.setTextColor(15, 15, 15);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(title, 14, 48);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(90, 90, 90);
  doc.text(subtitle, 14, 55);
  doc.setTextColor(15, 15, 15);
  return 66;
}

function drawFooter(doc: jsPDF): void {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i += 1) {
    doc.setPage(i);
    doc.setDrawColor(10, 143, 63);
    doc.setLineWidth(0.5);
    doc.line(14, h - 18, w - 14, h - 18);
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text(`BSDC · The Pride of Bangladesh · ${APP_URL}`, 14, h - 12);
    doc.text(`Page ${i} of ${pages}`, w - 40, h - 12);
  }
}

export async function generateReportPdf(input: ReportInput): Promise<Blob> {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = drawHeader(doc, input.title, input.subtitle, input.period);

  for (const section of input.sections) {
    if (y > 250) {
      doc.addPage();
      y = 24;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setFillColor(237, 251, 242);
    doc.rect(14, y - 5, doc.internal.pageSize.getWidth() - 28, 8, 'F');
    doc.text(section.title, 16, y);
    y += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    for (const row of section.rows) {
      if (y > 275) {
        doc.addPage();
        y = 24;
      }
      doc.text(row.label, 18, y);
      doc.setFont('helvetica', 'bold');
      doc.text(row.value, doc.internal.pageSize.getWidth() - 18 - doc.getTextWidth(row.value), y);
      doc.setFont('helvetica', 'normal');
      y += 6;
    }
    y += 4;
  }

  if (input.chartImages?.length) {
    for (const chart of input.chartImages) {
      if (y > 200) {
        doc.addPage();
        y = 24;
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text(chart.title, 14, y);
      y += 4;
      try {
        doc.addImage(chart.dataUrl, 'PNG', 14, y, 120, 60);
      } catch {
        doc.setFont('helvetica', 'normal');
        doc.text('Chart unavailable', 14, y + 8);
      }
      y += 66;
    }
  }

  const qr = await generateQrDataUrl(`${APP_URL}/admin`, 160);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(110, 110, 110);
  doc.text(`Generated by ${input.generatedBy} · Scan to verify in the BSDC admin console`, 14, Math.min(y + 6, 272));
  doc.addImage(qr, 'PNG', doc.internal.pageSize.getWidth() - 40, Math.min(y - 4, 252), 26, 26);
  drawFooter(doc);
  return doc.output('blob');
}

export interface LicenseCertificateInput {
  licenseNo: string;
  softwareName: string;
  version: string;
  ownerName: string;
  licenseType: string;
  issuedAt: number;
  verifyUrl: string;
  status: string;
}

export async function generateLicenseCertificate(input: LicenseCertificateInput): Promise<Blob> {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' });
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  doc.setFillColor(9, 115, 53);
  doc.rect(0, 0, w, h, 'F');
  doc.setFillColor(15, 15, 15);
  doc.roundedRect(10, 10, w - 20, h - 20, 4, 4, 'F');
  doc.setDrawColor(63, 197, 127);
  doc.setLineWidth(1.2);
  doc.roundedRect(13, 13, w - 26, h - 26, 3, 3);

  doc.setTextColor(63, 197, 127);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('BANGLADESH SOFTWARE DEVELOPMENT COMMUNITY', w / 2, 30, { align: 'center' });
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('OFFICIAL SOFTWARE LICENSE', w / 2, 44, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(180, 200, 190);
  doc.text('Verified by BSDC · The Pride of Bangladesh — Where Developers Unite', w / 2, 52, { align: 'center' });

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(input.softwareName, w / 2, 72, { align: 'center' });
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Version ${input.version} · ${input.licenseType} license · Status: ${input.status}`, w / 2, 80, { align: 'center' });

  doc.setFontSize(10);
  const rows: [string, string][] = [
    ['Registered owner', input.ownerName],
    ['License number', input.licenseNo],
    ['Issued on', formatDate(input.issuedAt, 'MMMM D, YYYY')],
    ['Verification', input.verifyUrl],
  ];
  let y = 100;
  for (const [label, value] of rows) {
    doc.setTextColor(150, 170, 160);
    doc.text(label.toUpperCase(), w / 2 - 90, y);
    doc.setTextColor(255, 255, 255);
    doc.text(value, w / 2 - 20, y);
    y += 10;
  }

  const qr = await generateQrDataUrl(input.verifyUrl, 220);
  doc.addImage(qr, 'PNG', w - 74, h - 88, 48, 48);
  doc.setTextColor(150, 170, 160);
  doc.setFontSize(8);
  doc.text('Scan to verify authenticity', w - 72, h - 34);
  doc.text('Issued by RRC Development · Rizwan Rahim Chowdhury, Founder & CEO', 22, h - 24);
  doc.text(APP_URL, 22, h - 19);
  return doc.output('blob');
}
