/**
 * The edits the generated native project needs, as pure functions.
 *
 * `android/` is produced by `npx cap add android` on every build and is not
 * committed, so anything the app needs beyond Capacitor's defaults has to be
 * re-applied each time. Doing that with a text editor on a CI runner is how
 * app links quietly stop working; doing it here means the rules are read,
 * reviewed and tested like everything else.
 *
 * Every function is idempotent: running the configuration twice must leave
 * the file exactly as it was after the first run.
 */

import { TRUSTED_HOSTS, APP_SCHEME } from './links.js';

/** Hosts whose https links this app is allowed to claim from the browser. */
export const APP_LINK_HOSTS = TRUSTED_HOSTS;

const MARKER = 'bsdc:intent-filters';

function intentFilters(): string {
  const hosts = APP_LINK_HOSTS.map(
    (host) => `        <data android:scheme="https" android:host="${host}" />`,
  ).join('\n');

  return [
    `      <!-- ${MARKER} — generated by scripts/configure-android.mjs -->`,
    '      <intent-filter android:autoVerify="true">',
    '        <action android:name="android.intent.action.VIEW" />',
    '        <category android:name="android.intent.category.DEFAULT" />',
    '        <category android:name="android.intent.category.BROWSABLE" />',
    hosts,
    '      </intent-filter>',
    '      <intent-filter>',
    '        <action android:name="android.intent.action.VIEW" />',
    '        <category android:name="android.intent.category.DEFAULT" />',
    '        <category android:name="android.intent.category.BROWSABLE" />',
    `        <data android:scheme="${APP_SCHEME}" />`,
    '      </intent-filter>',
  ].join('\n');
}

/**
 * Adds the app-link and custom-scheme intent filters to the main activity.
 *
 * `autoVerify` is set on the https filter only. Android checks
 * `/.well-known/assetlinks.json` on each host before it will open those
 * links in the app; until that file lists the release certificate, the
 * links keep opening in the browser, which is the correct failure.
 */
export function withIntentFilters(manifest: string): string {
  if (manifest.includes(MARKER)) return manifest;

  const activityEnd = manifest.indexOf('</activity>');
  if (activityEnd === -1) {
    throw new Error('AndroidManifest.xml has no <activity> to attach intent filters to');
  }
  return `${manifest.slice(0, activityEnd)}${intentFilters()}\n    ${manifest.slice(activityEnd)}`;
}

/**
 * Cleartext traffic is off, and stays off. Capacitor leaves it disabled by
 * default; this asserts it rather than trusting the default, because the
 * one thing a shell must never do is load its own product over plain HTTP.
 */
export function withoutCleartextTraffic(manifest: string): string {
  if (/android:usesCleartextTraffic="true"/.test(manifest)) {
    return manifest.replace(
      /android:usesCleartextTraffic="true"/g,
      'android:usesCleartextTraffic="false"',
    );
  }
  return manifest;
}

export interface Version {
  readonly code: number;
  readonly name: string;
}

/**
 * A version a human can read and a code Play can order.
 *
 * The code is the CI run number, which only ever increases; the name comes
 * from the tag when there is one and from the run number when there is not,
 * so an internal build is never mistaken for a release.
 */
export function versionFrom(tag: string, runNumber: number): Version {
  const cleaned = tag
    .trim()
    .replace(/^refs\/tags\//, '')
    .replace(/^android-v?/, '')
    .replace(/^v/, '');
  const isRelease = /^\d+\.\d+\.\d+$/.test(cleaned);
  return {
    code: Math.max(1, Math.trunc(runNumber)),
    name: isRelease ? cleaned : `0.0.0-build.${Math.max(1, Math.trunc(runNumber))}`,
  };
}

/** Writes the version into the Gradle file Capacitor generated. */
export function withVersion(gradle: string, version: Version): string {
  if (!/versionCode\s+\d+/.test(gradle) || !/versionName\s+"[^"]*"/.test(gradle)) {
    throw new Error('build.gradle has no versionCode or versionName to set');
  }
  return gradle
    .replace(/versionCode\s+\d+/, `versionCode ${version.code}`)
    .replace(/versionName\s+"[^"]*"/, `versionName "${version.name}"`);
}

/**
 * Adds the release signing configuration, reading every credential from the
 * environment at build time. Nothing is written into the file but the names
 * of the variables, so the Gradle file remains safe to print in a log.
 */
export function withReleaseSigning(gradle: string): string {
  if (gradle.includes('bsdc:signing')) return gradle;

  const signing = `
    // bsdc:signing — credentials come from the environment, never from a file.
    signingConfigs {
        release {
            if (System.getenv("BSDC_KEYSTORE_PATH")) {
                storeFile file(System.getenv("BSDC_KEYSTORE_PATH"))
                storePassword System.getenv("BSDC_KEYSTORE_PASSWORD")
                keyAlias System.getenv("BSDC_KEY_ALIAS")
                keyPassword System.getenv("BSDC_KEY_PASSWORD")
            }
        }
    }
`;

  const androidBlock = gradle.indexOf('android {');
  if (androidBlock === -1) throw new Error('build.gradle has no android block');
  const insertAt = gradle.indexOf('\n', androidBlock) + 1;
  let patched = `${gradle.slice(0, insertAt)}${signing}${gradle.slice(insertAt)}`;

  // Point the release build type at that configuration, and only it.
  patched = patched.replace(
    /buildTypes\s*{\s*release\s*{/,
    'buildTypes {\n        release {\n            signingConfig signingConfigs.release',
  );
  return patched;
}

/**
 * A Firebase configuration file good enough for Gradle to parse when no
 * real one is available. A debug build must not require a production
 * secret; a release build is given the real file by CI, and
 * `isPlaceholderConfig` is how the workflow refuses to publish one built
 * against this.
 */
export function placeholderGoogleServices(appId: string): string {
  return `${JSON.stringify(
    {
      project_info: {
        project_number: '000000000000',
        project_id: 'bsdc-placeholder',
        storage_bucket: 'bsdc-placeholder.appspot.com',
      },
      client: [
        {
          client_info: {
            mobilesdk_app_id: '1:000000000000:android:0000000000000000000000',
            android_client_info: { package_name: appId },
          },
          oauth_client: [],
          api_key: [{ current_key: 'placeholder-not-a-real-key' }],
          services: { appinvite_service: { other_platform_oauth_client: [] } },
        },
      ],
      configuration_version: '1',
    },
    null,
    2,
  )}\n`;
}

export function isPlaceholderConfig(contents: string): boolean {
  return contents.includes('bsdc-placeholder');
}
