/**
 * BSDC — src/shared/lib/uid.ts
 * Purpose : Identifier generation: short codes, referral codes, order ids, invoice numbers.
 * Owner   : RRC Development / BSDC Platform Team
 * Notes   : Firestore document ids are generated by the SDK; these helpers are for human-facing
 *           identifiers. The alphabet excludes look-alike glyphs so codes can be read aloud.
 * Licence : Source-available. Re-deployment or rebranding is not permitted.
 */

/** Alphabet without 0/O/1/I/L to avoid transcription errors. */
const BASE32 = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';

/**
 * Reads cryptographically strong random bytes.
 * @param length number of bytes
 * @returns Uint8Array of random bytes
 */
function randomBytes(length: number): Uint8Array {
  const bytes = new Uint8Array(length);
  const cryptoObj = globalThis.crypto;
  if (cryptoObj && typeof cryptoObj.getRandomValues === 'function') {
    cryptoObj.getRandomValues(bytes);
    return bytes;
  }
  for (let index = 0; index < length; index += 1) {
    bytes[index] = Math.floor(Math.random() * 256);
  }
  return bytes;
}

/**
 * Generates a URL-safe random id.
 * @param length character count (default 21)
 * @returns random id
 */
export function uid(length = 21): string {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  const bytes = randomBytes(length);
  let output = '';
  for (const byte of bytes) output += alphabet[byte % alphabet.length] ?? '';
  return output;
}

/**
 * Generates a base32 code in groups, e.g. BSDC-ADS-4K7P-9QRT.
 * @param prefix code prefix
 * @param groups number of groups
 * @param groupSize characters per group
 * @returns formatted code
 */
export function groupedCode(prefix: string, groups = 4, groupSize = 4): string {
  const parts: string[] = [];
  for (let group = 0; group < groups; group += 1) {
    const bytes = randomBytes(groupSize);
    let part = '';
    for (const byte of bytes) part += BASE32[byte % BASE32.length] ?? '';
    parts.push(part ?? '');
  }
  return [prefix, ...parts].join('-');
}

/**
 * Generates a short permalink code for /p/[shortId] (PART 07.03).
 * @returns 10-character short id
 */
export function shortPermalink(): string {
  const bytes = randomBytes(10);
  let output = '';
  for (const byte of bytes) output += BASE32[byte % BASE32.length] ?? '';
  return output ?? '';
}

/**
 * Builds a human-readable order id: BSDC-ORD-YYMMDD-XXXX.
 * @param date order date
 * @returns order id
 */
export function orderId(date: Date = new Date()): string {
  const year = String(date.getFullYear()).slice(2);
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const bytes = randomBytes(4);
  let suffix = '';
  for (const byte of bytes) suffix += BASE32[byte % BASE32.length] ?? '';
  return `BSDC-ORD-${year}${month}${day}-${suffix}`;
}

/**
 * Builds an ads invoice number: BSDC-ADS-YYYY-NNNNN (PART 21.1).
 * @param sequence monotonically increasing sequence for the year
 * @param date issue date
 * @returns invoice number
 */
export function invoiceNumber(sequence: number, date: Date = new Date()): string {
  return `BSDC-ADS-${date.getFullYear()}-${String(sequence).padStart(5, '0')}`;
}

/**
 * Generates a member referral code (F-001..F-070 onboarding).
 * @returns 8-character referral code
 */
export function referralCode(): string {
  const bytes = randomBytes(8);
  let output = '';
  for (const byte of bytes) output += BASE32[byte % BASE32.length] ?? '';
  return output ?? '';
}
