/**
 * BSDC — src/features/reactions/ReactionGlyph.tsx
 * Purpose : One reaction glyph, drawn from the published sprite.
 * Owner   : RRC Development / BSDC Platform Team
 * Notes   : Reactions are SVG, never emoji (LAW-01). The sprite is the single source: the app, an
 *   exported PDF and a notification e-mail all reference the same symbol id, so a reaction looks
 *   the same everywhere. `currentColor` inheritance keeps the glyph correct in every theme
 *   without a second asset.
 * Licence : Source-available. Re-deployment or rebranding is not permitted.
 */
import { reactionDefinition, type ReactionType } from '@/core/config/reactions';
import { cn } from '@/shared/lib/cn';

/** Path of the published sprite, generated by tools/generate-sprite.mjs. */
export const SPRITE_PATH = '/icons/sprite.svg';

/** Props for a reaction glyph. */
export interface ReactionGlyphProps {
  readonly type: ReactionType;
  readonly size?: number | undefined;
  readonly className?: string | undefined;
  /** Provide a label to expose the glyph to assistive technology. */
  readonly label?: string | undefined;
}

/**
 * Renders one reaction glyph.
 * @param props glyph props
 * @returns the glyph element
 */
export function ReactionGlyph({
  type,
  size = 20,
  className,
  label,
}: ReactionGlyphProps): React.ReactElement {
  const definition = reactionDefinition(type);
  return (
    <svg
      className={cn('bsdc-reaction-glyph', className)}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      data-tint={definition.tint}
      data-type={type}
      focusable="false"
      aria-hidden={label === undefined ? true : undefined}
      role={label === undefined ? undefined : 'img'}
      aria-label={label}
    >
      <use href={`${SPRITE_PATH}#${definition.spriteId}`} />
    </svg>
  );
}
