/**
 * BSDC — capacitor.config.ts
 * Purpose : Capacitor configuration for the BSDC Android application (PART 28).
 * Owner   : RRC Development / BSDC Platform Team
 * Notes   : The Android package id is `bd.info.bsdc.app` and it is not negotiable: it is the
 *   identity in the Play Store, the identity in the Firebase console and the identity in the
 *   deep-link and app-link configuration, and a mismatch between the three is an app that signs in
 *   on the web and opens a stranger on a phone.
 *   `webDir` points at `dist`, which is what the prerender step writes, so the packaged application
 *   is byte-for-byte the same build the website serves — no second pipeline, no second set of bugs.
 *   The native project itself (android/) is generated by `npx cap add android` on a machine with
 *   the Android SDK and is not committed: it is a build artefact of this file, not a source of
 *   truth. See PUBLIC_LIMITATIONS.md.
 * Licence : Source-available. Re-deployment or rebranding is not permitted.
 */
import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'bd.info.bsdc.app',
  appName: 'BSDC',
  webDir: 'dist',
  // The web build is the canonical build. Nothing is bundled twice and nothing is patched after
  // the fact, so a bug fixed on the site is fixed in the app in the same commit.
  loggingBehavior: 'none',
  plugins: {
    // A native shell that draws under the status bar and lets the keyboard cover the composer is
    // a native shell that looks broken, so both are configured here rather than in platform code.
    StatusBar: {
      style: 'default',
      backgroundColor: '#2d6a4f',
      overlaysWebView: false,
    },
    Keyboard: {
      resizeOnFullScreen: true,
      resize: 'body',
    },
    App: {
      // Hardware back must leave the application only from the top level. Anywhere else it is the
      // same thing the on-screen back control does, which is to go back one screen.
      enableBackButtonHandling: true,
    },
  },
  android: {
    // The application is Bangla-first: the launcher name, the web view locale and the build all
    // follow the device, and the manifest never hard-codes a language.
    allowMixedContent: false,
    captureInput: true,
    webContentsDebuggingEnabled: false,
    buildOptions: {
      keystorePath: undefined,
      keystoreAlias: 'bsdc',
    },
  },
  server: {
    // No remote origin is ever loaded inside the application. The bundle is the bundle: serving
    // part of an app from a URL is how a signed build starts running code nobody reviewed.
    androidScheme: 'https',
    cleartext: false,
  },
};

export default config;
