import { Phone, PhoneOff, Mic, MicOff, Volume2 } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import type { ChatParticipant } from '@/types/chat';
import type { CallState, IncomingCall } from '@/hooks/useVoiceCall';

export function VoiceCallPanel({ state, muted, incoming, peer, onStart, onAccept, onDecline, onEnd, onMute }: { state: CallState; muted: boolean; incoming: IncomingCall | null; peer: ChatParticipant | null; onStart: () => void; onAccept: () => void; onDecline: () => void; onEnd: () => void; onMute: () => void }) {
  if (incoming) return <div className="flex flex-wrap items-center gap-2 border-b border-brand-200 bg-brand-50 px-3 py-2 text-sm dark:border-brand-900 dark:bg-brand-950/40"><Volume2 className="h-4 w-4 text-brand-600" aria-hidden /><span className="min-w-0 flex-1 truncate">Incoming voice call from {incoming.caller.displayName || 'BSDC member'}</span><Button size="xs" onClick={onAccept} icon={<Phone className="h-3.5 w-3.5" aria-hidden />}>Accept</Button><Button size="xs" variant="outline" onClick={onDecline} icon={<PhoneOff className="h-3.5 w-3.5" aria-hidden />}>Decline</Button></div>;
  if (state === 'idle') return peer ? <button type="button" onClick={onStart} aria-label={`Call ${peer.displayName}`} className="bsdc-tap rounded-xl p-2 text-neutral-500 hover:bg-neutral-100 hover:text-brand-600 dark:hover:bg-surface-dark-raised"><Phone className="h-5 w-5" aria-hidden /></button> : null;
  return <div className="flex items-center gap-2 rounded-xl bg-brand-50 px-2 py-1.5 text-xs font-semibold text-brand-700 dark:bg-brand-950/50 dark:text-brand-300"><span className="capitalize">{state}</span><button type="button" onClick={onMute} className="bsdc-tap rounded-lg p-1.5" aria-label={muted ? 'Unmute microphone' : 'Mute microphone'}>{muted ? <MicOff className="h-4 w-4" aria-hidden /> : <Mic className="h-4 w-4" aria-hidden />}</button><button type="button" onClick={onEnd} className="bsdc-tap rounded-lg bg-red-500 p-1.5 text-white" aria-label="End call"><PhoneOff className="h-4 w-4" aria-hidden /></button></div>;
}