import {
  poishaToString,
  sum,
  trendPercent,
  type SnapshotPayload,
  type SnapshotSummary,
} from '@/lib/analytics/analytics-types';
import { PdfDocument } from './pdf';

function percentLabel(value: number | null): string {
  if (value === null) return 'n/a';
  return `${value > 0 ? '+' : ''}${String(value)}%`;
}

/**
 * Renders a stored snapshot as a PDF. It reads only the snapshot, never the
 * live database, so re-printing an old report reproduces the old numbers.
 */
export function buildReportPdf(summary: SnapshotSummary, payload: SnapshotPayload): Uint8Array {
  const document = new PdfDocument(summary.title);
  const totals = payload.totals;

  document
    .text('Bangladesh Software Development Community', { size: 9, grey: 0.45 })
    .text(summary.title, { size: 20, bold: true })
    .text(`Period ${summary.periodFrom} to ${summary.periodTo}`, { size: 10, grey: 0.4 })
    .text(
      `Snapshot taken ${payload.generatedAt.slice(0, 19).replace('T', ' ')} UTC. ` +
        'Figures are those recorded at that moment and are not recalculated on printing.',
      { size: 9, grey: 0.45 },
    )
    .rule();

  document.heading('Summary');
  document
    .keyValue('Members, all time', String(totals.membersTotal))
    .keyValue('Members joined in period', String(totals.membersPeriod))
    .keyValue('Posts, all time', String(totals.postsTotal))
    .keyValue('Posts in period', String(totals.postsPeriod))
    .keyValue('Reports still open', String(totals.reportsOpen))
    .keyValue('Marketplace turnover (BDT)', poishaToString(totals.grossSales))
    .keyValue('Commission earned (BDT)', poishaToString(totals.commission))
    .keyValue('Advertising spend (BDT)', poishaToString(totals.adSpend))
    .keyValue('Platform revenue (BDT)', poishaToString(totals.commission + totals.adSpend));

  if (payload.growth.length > 0) {
    const members = payload.growth.map((point) => point.newMembers);
    const posts = payload.growth.map((point) => point.newPosts);

    document.heading('Growth');
    document.text(
      `New members ${String(sum(members))} (${percentLabel(trendPercent(members))} ` +
        `against the first half of the period), new posts ${String(sum(posts))} ` +
        `(${percentLabel(trendPercent(posts))}).`,
      { size: 10 },
    );
    document.barChart({
      labels: payload.growth.map((point) => point.day),
      values: members,
    });
    document.text('New members per day', { size: 8, grey: 0.45 });
  }

  if (payload.revenue.length > 0) {
    const recent = payload.revenue.slice(-14);
    document.heading('Revenue, last 14 days of the period');
    document.table({
      columns: ['Day', 'Orders', 'Turnover', 'Commission', 'Ad spend'],
      rows: recent.map((point) => [
        point.day,
        String(point.ordersCount),
        poishaToString(point.grossSales),
        poishaToString(point.commission),
        poishaToString(point.adSpend),
      ]),
      widths: [110, 70, 110, 110, 99],
    });
  }

  document
    .space(10)
    .rule()
    .text(
      'Generated by the BSDC admin panel. Reports are written in English because the ' +
        'standard PDF fonts do not carry Bangla glyphs.',
      { size: 8, grey: 0.5 },
    );

  return document.build();
}

/** Hands the bytes to the browser as a download. */
export function downloadPdf(bytes: Uint8Array, filename: string): void {
  const buffer = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(buffer).set(bytes);
  const blob = new Blob([buffer], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

/** The same, for a CSV export of the underlying rows. */
export function downloadCsv(csv: string, filename: string): void {
  const blob = new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
