/**
 * BSDC — src/entities/conversation/model.ts
 * Purpose : Conversations and chat messages: shape, ids, titles and read state.
 * Owner   : RRC Development / BSDC Platform Team
 * Notes   : A direct conversation id is derived deterministically from the two participant ids,
 *   so opening the same chat twice never creates a duplicate thread and the id can be computed
 *   offline. Messages carry a client id as well as a server id: the client id is generated before
 *   the write, which lets an optimistic message and its server echo be deduplicated without
 *   flicker.
 *   `deliveredTo` and `readBy` hold account ids. Presence and typing live in the Realtime
 *   Database; only the durable message text lives here.
 * Licence : Source-available. Re-deployment or rebranding is not permitted.
 */
import { TEXT_LIMITS } from '@/core/config/limits';
import { sanitizeText } from '@/shared/lib/text';
import { uid } from '@/shared/lib/uid';

/** Kinds of conversation. */
export type ConversationKind = 'direct' | 'group';

/** A conversation thread. */
export interface Conversation {
  readonly id: string;
  readonly kind: ConversationKind;
  readonly title: string;
  readonly participantUids: readonly string[];
  /** Parallel to `participantUids`: display names, so the list needs no extra reads. */
  readonly participantNames: readonly string[];
  readonly participantPhotos: readonly string[];
  readonly avatarUrl: string;
  readonly lastMessagePreview: string;
  readonly lastMessageAt: string;
  readonly lastMessageSenderUid: string;
  /** Unread count per participant. The viewer's own entry is what the badge shows. */
  readonly unread: Readonly<Record<string, number>>;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
}

/** What a chat message carries. */
export type ChatMessageKind = 'text' | 'image' | 'document' | 'voice' | 'system';

/** An attachment inside a chat message. */
export interface ChatAttachment {
  readonly url: string;
  readonly provider: 'cloudinary' | 'imgbb';
  readonly remoteId: string;
  readonly width: number;
  readonly height: number;
  readonly bytes: number;
  readonly alt: string;
  readonly blurPreview: string;
  /** Duration in seconds for voice notes. */
  readonly durationSeconds: number;
}

/** A chat message. */
export interface ChatMessage {
  readonly id: string;
  /** Generated by the sender before the write; used to deduplicate the optimistic echo. */
  readonly clientId: string;
  readonly conversationId: string;
  readonly senderUid: string;
  readonly senderName: string;
  readonly senderPhotoUrl: string;
  readonly kind: ChatMessageKind;
  readonly body: string;
  readonly attachment: ChatAttachment | null;
  readonly replyToId: string;
  readonly deliveredTo: readonly string[];
  readonly readBy: readonly string[];
  readonly editedAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
}

/** Fields required to send a message. */
export interface NewMessageInput {
  readonly conversationId: string;
  readonly senderUid: string;
  readonly body: string;
  readonly kind?: ChatMessageKind | undefined;
  readonly attachment?: ChatAttachment | null | undefined;
  readonly replyToId?: string | undefined;
  readonly senderName?: string | undefined;
  readonly senderPhotoUrl?: string | undefined;
  readonly clientId?: string | undefined;
  readonly now?: Date | undefined;
}

/**
 * Derives the deterministic id of a direct conversation.
 * @param a first participant
 * @param b second participant
 * @returns a stable conversation id
 */
export function directConversationId(a: string, b: string): string {
  return [a, b].sort().join('--');
}

/**
 * Builds a chat message entity.
 * @param input composer values
 * @returns a complete message entity
 */
export function newMessage(input: NewMessageInput): ChatMessage {
  const now = (input.now ?? new Date()).toISOString();
  const id = uid();
  return {
    id,
    clientId: input.clientId ?? id,
    conversationId: input.conversationId,
    senderUid: input.senderUid,
    senderName: input.senderName ?? '',
    senderPhotoUrl: input.senderPhotoUrl ?? '',
    kind: input.kind ?? 'text',
    body: sanitizeText(input.body).slice(0, TEXT_LIMITS.chatMessage),
    attachment: input.attachment ?? null,
    replyToId: input.replyToId ?? '',
    deliveredTo: [input.senderUid],
    readBy: [],
    editedAt: null,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
  };
}

/**
 * Builds the empty shell of a conversation.
 * @param id conversation id
 * @param kind conversation kind
 * @param participants participant account ids
 * @param title display title
 * @returns a new conversation entity
 */
export function newConversation(
  id: string,
  kind: ConversationKind,
  participants: readonly string[],
  title = '',
): Conversation {
  const now = new Date().toISOString();
  const unread: Record<string, number> = {};
  for (const participant of participants) unread[participant] = 0;
  return {
    id,
    kind,
    title,
    participantUids: participants,
    participantNames: [],
    participantPhotos: [],
    avatarUrl: '',
    lastMessagePreview: '',
    lastMessageAt: now,
    lastMessageSenderUid: '',
    unread,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
  };
}

/**
 * Resolves the title to show for a conversation.
 * @param conversation the conversation
 * @param selfUid the viewer's account id
 * @param fallback fallback label for a thread with no title
 * @returns the title to render
 */
export function conversationTitle(
  conversation: Conversation,
  selfUid: string,
  fallback: string,
): string {
  if (conversation.title.trim().length > 0) return conversation.title;
  const index = conversation.participantUids.indexOf(selfUid);
  const others = conversation.participantNames.filter((_name, position) => position !== index);
  const joined = others.filter((name) => name.trim().length > 0).join(', ');
  return joined.length > 0 ? joined : fallback;
}

/**
 * Builds a short preview line for a conversation row.
 * @param message the last message
 * @param maxLength maximum length
 * @returns the preview text
 */
export function messagePreview(message: ChatMessage, maxLength = 60): string {
  const raw =
    message.kind === 'text'
      ? message.body
      : message.kind === 'image'
        ? 'Photo'
        : message.kind === 'voice'
          ? 'Voice note'
          : message.kind === 'document'
            ? 'Document'
            : message.body;
  return raw.length > maxLength ? `${raw.slice(0, maxLength - 1)}…` : raw;
}

/**
 * Reports whether a message has been read by everyone except the sender.
 * @param message the message
 * @param participantUids every participant in the conversation
 * @returns true when every recipient has read it
 */
export function isFullyRead(message: ChatMessage, participantUids: readonly string[]): boolean {
  return participantUids
    .filter((uid) => uid !== message.senderUid)
    .every((uid) => message.readBy.includes(uid));
}
