/// <reference lib="webworker" />
/**
 * The service worker: the offline shell, and the thing that answers a push.
 *
 * This used to be generated by Workbox from the plugin's configuration, which
 * can precache and fall back but cannot listen for anything — and a notification
 * that only arrives while the site is open is not a notification. So the worker
 * is written here, and it keeps every rule the generated one had: the precache
 * manifest, `/index.html` for a navigation that misses, the same denylist, the
 * same image and font caches with the same limits.
 *
 * A push arrives with no payload. The wake-up is empty — a body would have to be
 * encrypted for this one subscription — so the worker asks `/api/push/content`
 * what this device missed and writes it up. The endpoint is the capability: a
 * long random address only this browser, its push service and the database hold,
 * which is why the request needs no session. A device that has been asleep for a
 * day gets one summary, not nine buzzes.
 */
import type { WorkboxPlugin } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';

import {
  notificationBody,
  notificationTag,
  notificationTitle,
  parsePushContent,
  summarize,
  type PushContent,
} from '@/lib/notifications/copy';
import { urlBase64ToUint8Array } from '@/lib/push/webpush';

declare let self: ServiceWorkerGlobalScope;

const CONTENT_URL = '/api/push/content';
const ICON = '/icons/icon-192.png';
const BADGE = '/icons/maskable-512.png';
const VAPID_PUBLIC_KEY = import.meta.env.VITE_PUSH_VAPID_PUBLIC_KEY ?? '';

/**
 * `workbox-expiration` types its optional callbacks as `T | undefined`, which
 * `exactOptionalPropertyTypes` will not accept where `workbox-core` types them as
 * merely optional. It is the same object at either end; the cast belongs to the
 * type system, not to the runtime.
 */
function expire(maxEntries: number, maxAgeSeconds: number): WorkboxPlugin[] {
  return [new ExpirationPlugin({ maxEntries, maxAgeSeconds }) as unknown as WorkboxPlugin];
}

precacheAndRoute(self.__WB_MANIFEST);

// A navigation that is not in the precache gets the app shell, except where the
// shell would be a lie: the API, the Firebase callbacks, the feeds and the bots.
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('/index.html'), {
    denylist: [/^\/api\//, /^\/__\//, /^\/sitemap/, /^\/rss/, /^\/robots\.txt$/],
  }),
);

registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'bsdc-images',
    plugins: expire(200, 60 * 60 * 24 * 30),
  }),
);

registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'bsdc-fonts',
    plugins: expire(20, 60 * 60 * 24 * 365),
  }),
);

// The worker is registered as `prompt`: it waits, and the app decides when the
// member is told a new version is ready. Applying it is the app's message, not
// a decision made while somebody is reading.
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  const data = event.data as string | { type?: string } | undefined;
  const asked = typeof data === 'string' ? data : (data?.type ?? '');
  if (asked === 'SKIP_WAITING') void self.skipWaiting();
});

// ------------------------------------------------------------------- push ---

interface ContentAnswer {
  ok: boolean;
  items: PushContent[];
}

async function fetchContent(endpoint: string): Promise<ContentAnswer> {
  try {
    const response = await fetch(CONTENT_URL, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ endpoint, limit: 10 }),
    });
    if (!response.ok) return { ok: false, items: [] };
    return { ok: true, items: parsePushContent(await response.json()) };
  } catch {
    // No answer at all — a device that came online for a moment and lost it
    // again. The caller still shows something, because a push did arrive.
    return { ok: false, items: [] };
  }
}

function language(): 'bn' | 'en' {
  const tag = (self.navigator?.language ?? 'bn').toLowerCase();
  return tag.startsWith('en') ? 'en' : 'bn';
}

async function show(
  title: string,
  body: string,
  url: string,
  tag: string,
  icon?: string,
): Promise<void> {
  await self.registration.showNotification(title, {
    body,
    tag,
    icon: icon !== undefined && icon.length > 0 ? icon : ICON,
    badge: BADGE,
    lang: language(),
    dir: 'ltr',
    data: { url },
  });
}

async function handlePush(): Promise<void> {
  const subscription = await self.registration.pushManager.getSubscription();
  if (subscription === null) return;

  const answer = await fetchContent(subscription.endpoint);

  // The flush woke every device of this member; another one may already have
  // been told. Silence is better than a duplicate.
  if (answer.ok && answer.items.length === 0) return;

  const summary = summarize(answer.items);
  if (summary !== null) {
    await show(summary.title, summary.body, summary.url, `bsdc-summary-${Date.now()}`);
    return;
  }

  if (answer.items.length === 0) {
    await show(
      language() === 'en' ? 'BSDC' : 'বিএসডিসি',
      language() === 'en'
        ? 'Something new is waiting for you.'
        : 'আপনার জন্য নতুন কিছু অপেক্ষা করছে।',
      '/notifications',
      `bsdc-wake-${Date.now()}`,
    );
    return;
  }

  for (const item of answer.items) {
    await show(
      notificationTitle(item),
      notificationBody(item),
      item.url,
      notificationTag(item),
      item.actorAvatar,
    );
  }
}

self.addEventListener('push', (event: PushEvent) => {
  event.waitUntil(handlePush());
});

function urlOf(notification: Notification): string {
  const data = notification.data as { url?: unknown } | undefined;
  const url = typeof data?.url === 'string' ? data.url : '/notifications';
  return url.startsWith('/') ? url : '/notifications';
}

/**
 * Opens the thing the notification was about. A tab already on that page is
 * focused rather than duplicated; a tab elsewhere on the site is navigated, so
 * the member does not end up with a second copy of the app; only then is a
 * window opened.
 */
async function openTarget(url: string): Promise<void> {
  const target = new URL(url, self.location.origin).href;
  const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });

  for (const client of windows) {
    if (client.url === target) {
      await client.focus();
      return;
    }
  }

  const ours = windows.find((client) => {
    try {
      return new URL(client.url).origin === self.location.origin;
    } catch {
      return false;
    }
  });
  if (ours !== undefined) {
    try {
      const navigated = await ours.navigate(target);
      if (navigated !== null) {
        await navigated.focus();
        return;
      }
    } catch {
      // A tab with a half-written post can refuse to navigate; open a new one.
    }
  }

  await self.clients.openWindow(target);
}

self.addEventListener('notificationclick', (event: NotificationEvent) => {
  const url = urlOf(event.notification);
  event.notification.close();
  event.waitUntil(openTarget(url));
});

self.addEventListener('notificationclose', (event: NotificationEvent) => {
  // Nothing to undo, but a closed notification that stayed in the tray of a
  // device that reboots is a stale one; the tag makes the next push replace it.
  void event.notification.tag;
});

/**
 * The push service rotated this subscription — a browser update, a restored
 * profile, a key that expired. Re-subscribing keeps something deliverable on the
 * device; the app re-registers the new endpoint the next time it is opened,
 * which is the only moment it can prove who it belongs to. The old row is
 * retired by the flush when the push service answers 404.
 */
/**
 * The worker lib types this event as a plain `Event`, but at runtime it is an
 * `ExtendableEvent` that carries the replacement subscription. This is the part
 * of it that matters.
 */
interface SubscriptionChange {
  newSubscription?: PushSubscription | null;
  waitUntil(promise: Promise<unknown>): void;
}

self.addEventListener('pushsubscriptionchange', (event: Event) => {
  const change = event as Event & SubscriptionChange;
  change.waitUntil(
    (async () => {
      if (change.newSubscription) return;
      if (VAPID_PUBLIC_KEY.length === 0) return;
      try {
        await self.registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
        });
      } catch {
        // Permission can have been withdrawn while the site was closed. There is
        // nothing to subscribe with, and the app will ask again when it is open.
      }
    })(),
  );
});
