-- ---------------------------------------------------------------------------
-- Keep the profiles UPDATE grant aligned with the protected INSERT surface.
--
-- 0037 constrained a new member's first profile write, but the earlier UPDATE
-- grant still exposed `last_seen_at`. That timestamp is generated by trusted
-- presence/session work, not supplied by a browser. This migration re-states
-- the complete self-service update list without the activity column, so the
-- database grant, generated client types and application write payload agree.
-- ---------------------------------------------------------------------------

revoke update on public.profiles from authenticated;

grant update (
  username,
  display_name,
  bio,
  avatar_url,
  cover_url,
  location,
  website,
  skills,
  interests,
  language,
  onboarding_complete,
  notifications,
  privacy
) on public.profiles to authenticated;
